version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feedback-collector-backup"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-XXXXXXXXXXXX"
s3_prefix = "feedback-collector"
region = "us-east-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM"]
parameter_overrides = "Environment=dev" 